### ISSUE TITLE
defaultChecked should be a boolean

### ISSUE THREAD

**Issue by Kingles** [gfazioli/react-switch-button#14]
see: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
Specifically: 

HTMLInputElement.defaultChecked
Is a Boolean representing the default state of a radio button or checkbox as originally specified in HTML that created this object.

**Comment by erichirlemann** [comment]
+1

**Comment by CestDiego** [comment]
+1

**Comment by gfazioli** [comment]
done in v2.0.0
