### ISSUE TITLE
2.0.1 issue on ES6 import

### ISSUE THREAD

**Issue by benjamindulau** [gfazioli/react-switch-button#18]
It seems that importing with ES6 doesn't work.

```javascript
import SwitchButton from 'react-switch-button';
```

This throws the following error using webpack:

```
ERROR in ./~/react-switch-button/src/react-switch-button.js
Module parse failed: /vagrant/src/scripts/app/node_modules/react-switch-button/src/react-switch-button.js Unexpected token (70:8)
You may need an appropriate loader to handle this file type.
```

Any idea?

**Comment by gfazioli** [comment]
@benjamindulau mmm strange, let me check

**Comment by gfazioli** [comment]
@benjamindulau I fond that http://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b

**Comment by benjamindulau** [comment]
@gfazioli Yeah but I shouldn't have to include any vendor dependency in my Webpack loaders.

My guess is that you should publish an already transpiled version on NPM so I don't have to include the library in my babel/jsx loaders. Not sure about that though but I don't have any issue with any other library ATM.

**Comment by lironess** [comment]
@gfazioli, I think you just have to change this on package.json:
```javascript
"main": "src/react-switch-button.js",
```
to:
```javascript
"main": "dist/react-switch-button.js",
```

**Comment by lironess** [comment]
thanks !
but i forgot one property .. I'll submit a PR now
