### ISSUE TITLE
How to import using require?

### ISSUE THREAD

**Issue by owais** [gfazioli/react-switch-button#2]
Looks like we can't import this by doing something like

```
var Switch = require('react-switch-button');
```

Throws CompileError.

```
CompilerError: 
.../node_modules/react-switch-button/index.html:1
<!DOCTYPE html>
^
ParseError: Unexpected token
```

**Comment by owais** [comment]
@gfazioli bump.

**Comment by gfazioli** [comment]
@owais Hi there,
I'm investigating... I don't understand because it's loading `index.html`...

**Comment by gfazioli** [comment]
@owais 
I'm seeing similar issues on the web ... try this...

``` js
var Switch = require('react-switch-button').SwitchButton;
```

**Comment by owais** [comment]
Doesn't work. Same issue. Have you tried exporting the class from the module so browserify and friends can use it?

like, 

```
module.exports = {SwitchButton: SwitchButton}
```

**Comment by emilian** [comment]
You also need to transpile from JSX to JS and then make the switch button available like this:

`module.exports = React.createclass({..blah blah..});`

**Comment by ondrejhlavacek** [comment]
+1

**Comment by tcw165** [comment]
Did you publish it again by using `npm publish` to the server? I just downloaded from `npm install react-switch-button` and it's still old.
In addition, I suggest to add `module.exports = SwitchButton` so that developers can use arbitrary assets manager like `browserify` or `webpack` in **Node.js** way.

**Comment by smnplk** [comment]
+1 

Can you please publish 1.0.5 version ?
