### ISSUE TITLE
reactify / react-tools are deprecated

### ISSUE THREAD

**Issue by vdh** [gfazioli/react-switch-button#21]
react-tools has been deprecated and replaced by [Babel](https://github.com/babel/babel)

From [reactify's github page](https://github.com/andreypopp/reactify):
> **DEPRECATED:** Use [babelify](https://github.com/babel/babelify) instead (make sure you configured Babel with babel-preset-react).

A warning from yarn:
> warning react-switch-button > reactify > react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated

**Comment by gfazioli** [comment]
@vdh please, can you check last version?

**Comment by vdh** [comment]
@gfazioli looks good to me ;)
