### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createClass' of undefined

### ISSUE THREAD

**Issue by obykoo** [gfazioli/react-switch-button#23]
Installed fresh version from npm:

`npm install react-switch-button --save`

`-- react-switch-button@2.2.0`

And getting "Uncaught TypeError: Cannot read property 'createClass' of undefined" on import

Importing like this:

`import SwitchButton from 'react-switch-button';`

also tried this according to "ReadMe":

`import Select from 'react-switch-button';`
`import Switch from 'react-switch-button';`

**Comment by gfazioli** [comment]
@obykoo hi, sorry, it's a typo in docs, you should use

```SwitchButton = require( 'react-switch-button' );```

**Comment by briva** [comment]
I have same bug with : 

import SwitchButton from 'react-switch-button';

**Comment by Koiek2** [comment]
@gfazioli 
this does not seem to work either, I have the same problem

**Comment by briva** [comment]
Btw, another issue with webpack :

```
./~/react-switch-button/dist/react-switch-button.min.js
Critical dependencies:
1:419-426 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-switch-button/dist/react-switch-button.min.js 1:419-426
```

**Comment by gfazioli** [comment]
@briva @Koiek2 I just issued a minor version with default export. Please, let me know if something is changed. Unfortunately, I cannot replicate that error.

**Comment by ttsui** [comment]
@gfazioli I'm getting the same error with v2.2.1. The error went away when I changed the following in `package.json`. I'm using create-react-app tooling, i.e. webpack, etc.

```
--- package.json-	2017-03-04 00:54:37.000000000 +1100
+++ package.json	2017-03-04 00:54:41.000000000 +1100
@@ -23,7 +23,7 @@
     "gulp": "^3.9.1",
     "react-component-gulp-tasks": "^0.7.7"
   },
-  "browser": "dist/react-switch-button.min.js",
+  "browser": "lib/react-switch-button.js",
   "browserify": {
     "transform": [
       "babelify"
```

**Comment by gfazioli** [comment]
@ttsui if now it works could you open a pull request?

**Comment by jshimko** [comment]
I can confirm this still doesn't work as documented.  Same issue as everyone else.

<img width="561" alt="localhost_3000_users" src="https://cloud.githubusercontent.com/assets/3077956/23826570/857eb0cc-066c-11e7-91d3-4bf6fb22eab3.png">

**Comment by wzup** [comment]
I have the same issue

![switch - google chrome 2017-03-12 15 48 49](https://cloud.githubusercontent.com/assets/3880497/23830034/8d60a212-073b-11e7-9ffd-39776021f5ed.png)

And also a warning
```
WARNING in ./~/react-switch-button/dist/react-switch-button.min.js
Critical dependencies:
1:419-426 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-switch-button/dist/react-switch-button.min.js 1:419-426
```

**Comment by gfazioli** [comment]
@jshimko @wzup please, could you try to replace

```
-  "browser": "dist/react-switch-button.min.js",
+  "browser": "lib/react-switch-button.js",
```

as suggested by @ttsui ?

**Comment by seanmpage** [comment]
^ Suggestion fixed it for me...in the node_module package.json

**Comment by gfazioli** [comment]
@seanmpage can you create a PR?

**Comment by gfazioli** [comment]
closed https://github.com/gfazioli/react-switch-button/pull/24

**Comment by figalex** [comment]
Is this fix already published on npm? I just tried to install it and use the component but I got the same error. I had to do this:

`
import SwitchButton from 'react-switch-button/lib/react-switch-button.js';
`

**Comment by gfazioli** [comment]
@figalex published right now

**Comment by figalex** [comment]
I'm using webpack also for my server bundle and this error keeps coming up when server tries to render this component because is trying to use the .min.js version. I guess I'll just keep importing from /lib folder, it works and it seems like a very specific use case.
