### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by zaunermax** [gfazioli/react-switch-button#25]
## Problem 💥 

when using this component, there is a warning that `React.createClass()` will be removed in React version 16. 

## Solution 🤔 

The package [create-react-class](https://www.npmjs.com/package/create-react-class) should be used instead of the function from the React base package.

**Comment by Carlinho89** [comment]
will this be fixed or the repo is dead?

**Comment by gfazioli** [comment]
@Maxincredible52 @Carlinho89 fixed in v2.3.0
