### ISSUE TITLE
change `label_right` to `labelRight` in documentation

### ISSUE THREAD

**Issue by arslan-arrivy** [gfazioli/react-switch-button#29]
Hello,

I was checking your documentation and example at http://gfazioli.github.io/react-switch-button/ and found out that the example still shows the old prop `label_right`. 
Please update the documentation to address the proper prop i.e., `labelRight`. 

Thanks.

**Comment by arslan-arrivy** [comment]
Or please assign the issue to me at https://github.com/arximughal. I'll be happy to assist.

**Comment by gfazioli** [comment]
@arslan-arrivy assigned, thx

**Comment by Darkilen** [comment]
It's not resolved. Pull request #30 was not merged.

**Comment by arximughal** [comment]
@gfazioli Can you please merge the https://github.com/gfazioli/react-switch-button/pull/30 ?
