### ISSUE TITLE
Detail page has no demos?

### ISSUE THREAD

**Issue by winkler1** [gfazioli/react-switch-button#3]
Hi - don't see any demos of the actual component on http://gfazioli.github.io/react-switch-button/, expected to. I'd like to add to react.rocks, if there are demos. Thanks :)

**Comment by gfazioli** [comment]
Hi there,
sorry for the mistake, the demo page is the `index.html` in the repo.
Please, download/clone the repo in order to try the component.

Let me know if I can help you.

P.S.
Now I'll try ti put the demo file on the github page in order to display an online demo page.

**Comment by gfazioli** [comment]
@winkler1 ok, new you see the demo http://gfazioli.github.io/react-switch-button/#demo

**Comment by winkler1** [comment]
Thanks!
