### ISSUE TITLE
I get Module parse failed: Unexpected token (31:8) when trying to load it with webpack

### ISSUE THREAD

**Issue by capaj** [gfazioli/react-switch-button#35]
My project is in typescript so I don't have babel installed. 
```
ERROR in ./node_modules/react-switch-button/src/react-switch-button.jsx
Module parse failed: Unexpected token (31:8)
You may need an appropriate loader to handle this file type.
|
|       return (
|         <div className={classes.join( " " ).trim()}>
|           {
|             (this.props.label.length > 0)
 @ ./src/Wallet.tsx 23:28-58
 @ ./src/Dashboard.tsx
 @ ./src/main.tsx
 @ multi webpack-dev-server/client?http://localhost:3300 webpack/hot/only-dev-server ./src/main
```

That should not matter though because it should all run from the dist files right?

**Comment by abdennour** [comment]
The same

**Comment by MarcelLZ** [comment]
The same

**Comment by btbensoft** [comment]
Same here...

**Comment by shadowangle** [comment]
The same...

**Comment by anchorhan** [comment]
the same...

**Comment by nicecue** [comment]
same here

**Comment by istirbu** [comment]
same

**Comment by taboca** [comment]
same - how are you guys fixing the actual use case / workaround?

**Comment by dgaido** [comment]
Same, unusable..

**Comment by gfazioli** [comment]
Hey, I've created a new fresh component here https://github.com/gfazioli/react-toggle

It's the same component but now working fine. Use `yarn add react-toggle-component`

and `import Toggle from "react-toggle-component"`

With this new version, you don't need to load the styles. They are embedded.

Let me know if everything is ok

**Comment by capaj** [comment]
Well I've been on GitHub for a several years now, but this is the first time a maintainer resolved a bug by publishing a new package. @gfazioli why not just publish a new major?

**Comment by gfazioli** [comment]
@capaj hi, yes, I could fix everything here in this repo, but I needed to change the name of the package. This because I'll release others components. Also, I didn't like "switch", IMHO "toggle" is more correct and probably. In fact, I'll release a "react-switch-component" as well. It will be something different than the "toggle". So, in short, I have had to change the repo to avoid the mess.
