### ISSUE TITLE
Jest Cannot find module 'react-switch-button'

### ISSUE THREAD

**Issue by arsenslyusarchuk** [gfazioli/react-switch-button#38]
@gfazioli  During running tests with Jest I have the following issue `Cannot find module 'react-switch-button' from ...(some js file)`.
Getting into source code of library under `node_modules` I see typo in `package.json`
`"main": "dist/react-switch-button.min.js", `, which doesn't correspond to actual name under `dist` folder `react-switch-button.js` (without `min`). Please fix this typo, because changing name to `react-switch-button.min.js` makes the tests pass. 
Thanks.

**Comment by arsenslyusarchuk** [comment]
@gfazioli Hello, can anybody fix this issue?

**Comment by gfazioli** [comment]
@arsenslyusarchuk should be ok in `v2.3.4`

**Comment by gfazioli** [comment]
@arsenslyusarchuk better the `v2.3.5`

**Comment by arsenslyusarchuk** [comment]
@gfazioli Thanks, it works in `v.2.3.5`
