### ISSUE TITLE
Event is not  triggering  at all and  not working  in  IE and Mozilla browser 11

### ISSUE THREAD

**Issue by sairam356** [gfazioli/react-switch-button#39]
Please  provide  the solution  for  this

**Comment by gfazioli** [comment]
Hey, I've created a new fresh component here https://github.com/gfazioli/react-toggle

It's the same component but now working fine. Use `yarn add react-toggle-component`

and `import Toggle from "react-toggle-component"`

With this new version, you don't need to load the styles. They are embedded.

Let me know if everything is ok
